# Generated by Django 6.0.6 on 2026-07-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0003_add_performance_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="mbid",
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="artist",
            name="mbid",
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="song",
            name="mbid",
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
