# Generated by Django 6.0.6 on 2026-07-07 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0004_add_musicbrainz_mbids"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="cover_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="artist",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="favoritesong",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_songs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="favoritesong",
            name="session_key",
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.RemoveConstraint(
            model_name="favoritesong",
            name="unique_session_song_favorite",
        ),
        migrations.AddConstraint(
            model_name="favoritesong",
            constraint=models.UniqueConstraint(
                condition=models.Q(session_key__isnull=False),
                fields=("session_key", "song"),
                name="unique_session_song_favorite",
            ),
        ),
        migrations.AddConstraint(
            model_name="favoritesong",
            constraint=models.UniqueConstraint(
                condition=models.Q(user__isnull=False),
                fields=("user", "song"),
                name="unique_user_song_favorite",
            ),
        ),
    ]
