# Generated by Django 6.0.6 on 2026-07-07 17:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_metadatareport_likesong'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='metadatareport',
            index=models.Index(fields=['status', 'created_at'], name='music_metad_status_304ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='metadatareport',
            index=models.Index(fields=['issue_type', 'created_at'], name='music_metad_issue_t_d9cff9_idx'),
        ),
        migrations.AddConstraint(
            model_name='metadatareport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('album__isnull', True), ('artist__isnull', True), ('song__isnull', False)), models.Q(('album__isnull', False), ('artist__isnull', True), ('song__isnull', True)), models.Q(('album__isnull', True), ('artist__isnull', False), ('song__isnull', True)), _connector='OR'), name='metadata_report_exactly_one_target'),
        ),
    ]
